apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-client
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-client
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-client
        tier: api
    spec:
      containers:
      - name: {{ .Release.Name }}-client
        image: jgsqware/todo-frontend:0.2
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/nginx/html/config.js
          subPath: config.js
          readOnly: true
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      volumes:
      - name: config-volume
        configMap:
          name: {{ .Release.Name }}-client
