apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-client
  labels:
    chart: "{{ .Release.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: {{ .Release.Name }}-client
  selector:
    app: {{ .Release.Name }}-client