apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-bench-sa

---

apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: kube-bench
spec:
  hostPID: true
  allowPrivilegeEscalation: false
  fsGroup:
    ranges:
    - max: 65535
      min: 1
    rule: MustRunAs
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    ranges:
    - max: 65535
      min: 1
    rule: MustRunAs
  volumes:
  - secret
  - configMap
  - hostPath

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-bench
rules:
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - kube-bench
  verbs:
  - use

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-bench
subjects:
- kind: ServiceAccount
  name: kube-bench-sa
  namespace: kube-bench
roleRef:
  kind: ClusterRole
  name: kube-bench
  apiGroup: rbac.authorization.k8s.io