apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: core.<YOUR-NAME>.qjif7.k8s.gollum.westeurope.azure.gigantic.io/securityworkshop/nginx:1.12-alpine
  imagePullSecrets:
    - name: harbor-registry