apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ template "mongodb.fullname" . }}
spec:
  allowPrivilegeEscalation: false
  fsGroup:
    ranges:
    - max: 65535
      min: 1
    rule: MustRunAs
  runAsUser:
    rule: MustRunAsNonRoot
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    ranges:
    - max: 65535
      min: 1
    rule: MustRunAs
  volumes:
  - secret
  - configMap
  - persistentVolumeClaim
  - emptyDir

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "mongodb.fullname" . }}
rules:
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - {{ template "mongodb.fullname" . }}
  verbs:
  - use

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "mongodb.fullname" . }}
subjects:
- kind: ServiceAccount
  name: "{{ .Values.serviceAccount}}"
  namespace: "{{ .Release.Namespace }}"
roleRef:
  kind: ClusterRole
  name: {{ template "mongodb.fullname" . }}
  apiGroup: rbac.authorization.k8s.io